module.exports = ({ theme, animateIn }) => ({
  '.form-bar-root': {
    display: 'flex',
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1035,
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto',
    ...animateIn(theme),
    '--tw-enter-opacity': '0',
    '--tw-enter-translate-y': '33.33%',
    [`@media (min-width: ${theme('screens.sm')})`]: {
      marginBottom: '1rem',
      marginTop: '0.5rem',
    },
  },
  '.form-bar-content': {
    display: 'flex',
    maxWidth: '36rem',
    padding: '1rem',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    alignContent: 'center',
    gap: '1rem',
    width: '100%',
    flex: '1 0 0',
    flexWrap: 'wrap',
    borderTop: `1px solid ${theme('borderColor.default')}`,
    backgroundColor: theme('backgroundColor.default'),
    [`@media (min-width: ${theme('screens.sm')})`]: {
      alignItems: 'center',
      padding: '0.625rem 0.625rem 0.625rem 1rem',
      borderRadius: '1rem',
      borderWidth: '0px',
      boxShadow: theme('boxShadow.hard-lg'),
    },
  },
})
