module.exports = ({
  theme,
  textContentLabelStyles,
  transitionColorsStyles,
  animateIn,
  animateOut,
  transitionAllStyles,
}) => ({
  '.sidebar-provider': {
    display: 'flex',
    minHeight: '100svh',
    width: '100%',
  },
  '.sidebar-overlay': {
    position: 'fixed',
    inset: '0px',
    zIndex: '1030',
    backgroundColor: theme('colors.black-a10'),
    '&[data-force-mount="false"][data-state="open"]': {
      ...animateIn(theme),
      '--tw-enter-opacity': '0',
    },
    '&[data-force-mount="false"][data-state="closed"]': {
      ...animateOut(theme),
      '--tw-exit-opacity': '0',
    },
    '&[data-force-mount="true"][data-state="open"]': {
      ...transitionAllStyles(theme),
      visibility: 'visible',
      opacity: '1',
    },
    '&[data-force-mount="true"][data-state="closed"]': {
      ...transitionAllStyles(theme),
      visibility: 'hidden',
      opacity: '0',
    },
  },
  '.sidebar-root': {
    display: 'none',
    [`@media (min-width: ${theme('screens.sm')})`]: {
      display: 'block',
    },
    '&[data-collapsible="offcanvas"] .sidebar-gap': {
      width: '0px',
    },
    '&[data-side="right"] .sidebar-gap': {
      transform: 'rotate(180deg)',
    },
    '&[data-collapsible="offcanvas"] .sidebar-container[data-side="left"]': {
      left: 'calc(var(--sidebar-width) * -1)',
    },
    '&[data-collapsible="offcanvas"] .sidebar-container[data-side="right"]': {
      right: 'calc(var(--sidebar-width) * -1)',
    },
    '& .sidebar-gap': {
      width: 'var(--sidebar-width)',
    },
  },
  '.sidebar-gap': {
    position: 'relative',
    height: '100svh',
    backgroundColor: 'transparent',
    transitionProperty: 'width',
    transitionDuration: '200ms',
    animationDuration: '200ms',
    transitionTimingFunction: 'linear',
    animationTimingFunction: 'linear',
  },
  '.sidebar-container': {
    position: 'fixed',
    top: '0px',
    bottom: '0px',
    zIndex: '1035',
    display: 'none',
    height: '100svh',
    width: 'var(--sidebar-width)',
    transitionProperty: 'left,right,width',
    transitionDuration: '200ms',
    animationDuration: '200ms',
    transitionTimingFunction: 'linear',
    animationTimingFunction: 'linear',
    [`@media (min-width: ${theme('screens.sm')})`]: {
      display: 'flex',
    },
    '&[data-side="left"]': {
      left: '0px',
    },
    '&[data-side="right"]': {
      right: '0px',
    },
  },
  '.sidebar': {
    display: 'flex',
    height: '100%',
    width: '100%',
    flexDirection: 'column',
    backgroundColor: theme('backgroundColor.accent.gray-light'),
  },
  '.sidebar-header': {
    display: 'flex',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '1rem',
  },
  '.sidebar-footer': {
    display: 'flex',
    width: '100%',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  '.sidebar-content': {
    display: 'flex',
    flex: '1 1 0%',
    minHeight: '0px',
    width: '100%',
    flexDirection: 'column',
    overflow: 'auto',
    alignItems: 'flex-start',
    gap: '0.75rem',
  },
  '.sidebar-group': {
    position: 'relative',
    display: 'flex',
    width: '100%',
    minWidth: '0px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '0.125rem',
    padding: '0.5rem',
  },
  '.sidebar-group-label': {
    width: '100%',
    padding: '0.625rem 0.75rem',
    color: theme('textColor.subtler'),
    ...textContentLabelStyles(theme),
  },
  '.sidebar-menu': {
    display: 'flex',
    width: '100%',
    gap: '0.125rem',
    minWidth: '0px',
    flexDirection: 'column',
  },
  '.sidebar-menu-item': {
    position: 'relative',
  },
  '.sidebar-menu-button': {
    display: 'flex',
    width: '100%',
    padding: '0.5rem 0.75rem',
    alignItems: 'center',
    gap: '1rem',
    borderRadius: '0.75rem',
    outline: '2px solid transparent',
    outlineOffset: '2px',
    ...transitionColorsStyles(theme),
    '&:hover': {
      backgroundColor: theme('backgroundColor.interactive.hover'),
    },
    '&:focus-visible': {
      outlineOffset: '0px',
      outline: `2px solid ${theme('outlineColor.focus-ring')}`,
    },
    '&[data-active="true"]': {
      backgroundColor: theme('backgroundColor.interactive.pressed'),
    },
    '&.avatar': {
      width: 'auto',
      padding: '0.5rem',
      gap: '0.625rem',
    },
  },
})
