module.exports = ({ theme }) => ({
  '.file-input-container': {
    display: 'flex',
    padding: '0.875rem 0.75rem',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '0.5rem',
    width: '100%',
    alignSelf: 'stretch',
    borderRadius: '1rem',
    border: `1px dashed ${theme('borderColor.bold')}`,
    backgroundColor: theme('backgroundColor.default'),
    position: 'relative',
    outline: '2px solid transparent',
    outlineOffset: '2px',
    '&:hover, &.dragover': {
      backgroundColor: theme('backgroundColor.interactive.hover'),
    },
    '&:focus-visible': {
      outlineOffset: '0px',
      outline: `2px solid ${theme('outlineColor.focus-ring')}`,
    },
    '&:disabled, &.disabled': {
      cursor: 'not-allowed',
      pointer: 'none',
      borderColor: theme('borderColor.interactive.disabled'),
    },
    '& > svg, & > .mui-icon': {
      width: '1.75rem',
      minWidth: '1.75rem',
      height: '1.75rem',
      minHeight: '1.75rem',
      fontSize: '1.75rem',
      color: theme('colors.icon.subtle'),
    },
  },
  '.file-input-wrapper': {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '0.5rem',
  },
  '.input-file': {
    opacity: 0,
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    cursor: 'pointer',
    '&::-webkit-file-upload-button': {
      cursor: 'pointer',
    },
  },
  '.uploaded-file-container': {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    borderRadius: '0.75rem',
    border: `1px solid ${theme('borderColor.default')}`,
    backgroundColor: theme('backgroundColor.default'),
    boxShadow: theme('boxShadow.soft-xs'),
    '& .uploaded-file:not(:first-child)': {
      borderTop: `1px solid ${theme('borderColor.default')}`,
    },
  },
  '.uploaded-file': {
    display: 'flex',
    width: '100%',
    padding: '0.75rem 1rem',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
})
