module.exports = ({
  theme,
  transitionAllStyles,
  textContentStyles,
  transitionColorsStyles,
}) => ({
  '.tabs-list': {
    display: 'flex',
    flex: '1 1 0%',
    alignItems: 'center',
    gap: '1.5rem',
    borderBottomWidth: '1px',
    borderColor: 'transparent',
    paddingTop: '0.25rem',
  },
  '.tabs-list-fully-borderless': {
    gap: '1rem',
    border: 'none',
    padding: '0',
  },
  '.tabs-list-bordered': {
    borderColor: theme('borderColor.default'),
  },
  '.tabs-list-full-width': {
    gap: '0',
    '& .tabs-trigger': {
      width: '100%',
    },
  },
  '.tabs-list-fully-borderless.tabs-list-full-width': {
    gap: '1rem',
  },
  '.tabs-list:not(.tabs-list-fully-borderless) .tabs-trigger': {
    marginBottom: '-1px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    whiteSpace: 'nowrap',
    borderBottomWidth: '1px',
    borderColor: 'transparent',
    padding: '0.125rem 0.5rem 0.5rem 0.5rem',
    color: theme('textColor.subtle'),
    outline: '2px solid transparent',
    outlineOffset: '2px',
    ...transitionAllStyles(theme),
    ...textContentStyles(theme),
    '& > * > svg, & > * > .mui-icon': {
      height: '1rem',
      minHeight: '1rem',
      width: '1rem',
      minWidth: '1rem',
      fontSize: theme('fontSize.base'),
      color: theme('colors.icon.subtle'),
    },
    '& > *': {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '0.5rem',
      borderRadius: '0.75rem',
      backgroundColor: 'transparent',
      padding: '0.375rem 0.625rem',
      outline: '2px solid transparent',
      outlineOffset: '2px',
      ...transitionAllStyles(theme),
    },
    '&:hover > *': {
      backgroundColor: theme('backgroundColor.interactive.hover'),
    },
    '&:focus-visible > *': {
      outlineOffset: '0px',
      outline: `2px solid ${theme('outlineColor.focus-ring')}`,
    },
    '&[data-state="active"]': {
      borderColor: theme('borderColor.interactive.activated'),
      color: theme('textColor.brand.DEFAULT'),
    },
    '&[data-state="active"] > *': {
      backgroundColor: theme('backgroundColor.interactive.activated'),
      color: theme('textColor.interactive.activated'),
    },
    '&[data-state="active"] > * > svg, &[data-state="active"] > * > .mui-icon':
      {
        color: theme('colors.icon.activated'),
      },
  },
  '.tabs-list-fully-borderless .tabs-trigger': {
    display: 'flex',
    height: '2.25rem',
    minHeight: '2.25rem',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    borderRadius: '0.75rem',
    backgroundColor: theme('backgroundColor.default'),
    border: `1px solid ${theme('borderColor.default')}`,
    padding: '0.375rem 0.625rem',
    color: theme('textColor.subtle'),
    outline: 'none',
    outlineOffset: '0px',
    ...transitionColorsStyles(theme),
    ...textContentStyles(theme),
    '& > span': {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '0.5rem',
    },
    '& svg, & .mui-icon': {
      color: theme('colors.icon.subtle'),
      fontSize: theme('fontSize.base'),
      height: '1rem',
      minHeight: '1rem',
      width: '1rem',
      minWidth: '1rem',
    },
    '&:hover': {
      border: '1px solid transparent',
      backgroundColor: theme('backgroundColor.interactive.hover'),
    },
    '&:active': {
      border: '1px solid transparent',
      backgroundColor: theme('backgroundColor.interactive.hover'),
    },
    '&:focus-visible': {
      outlineOffset: '0px',
      outline: `2px solid ${theme('outlineColor.focus-ring')}`,
    },
    '&[data-state="active"]': {
      backgroundColor: theme('backgroundColor.interactive.activated'),
      border: '1px solid transparent',
      color: theme('textColor.interactive.activated'),
    },
    '&[data-state="active"] svg, &[data-state="active"] .mui-icon': {
      color: theme('colors.icon.activated'),
    },
  },
  '.tabs-content': {
    padding: '0.5rem 0',
  },
})
