module.exports = ({ theme, h2Styles, textContentParagraphStyles }) => ({
  '.drawer-overlay': {
    position: 'fixed',
    inset: '0px',
    zIndex: 1050,
    backgroundColor: theme('colors.black-a10'),
  },
  '.drawer-handle': {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.75rem 1.5rem 0.25rem 1.5rem',
    '&::after': {
      content: '""',
      height: '0.25rem',
      minHeight: '0.25rem',
      width: '3.5rem',
      minWidth: '3.5rem',
      borderRadius: '1rem',
      backgroundColor: theme('backgroundColor.accent.gray-intense'),
    },
  },
  '.drawer-content': {
    position: 'fixed',
    left: '0px',
    right: '0px',
    bottom: '0px',
    zIndex: 1055,
    display: 'flex',
    height: 'auto',
    maxHeight: 'calc(100vh - 6rem)',
    flexDirection: 'column',
    borderTopLeftRadius: '1rem',
    borderTopRightRadius: '1rem',
    backgroundColor: theme('backgroundColor.default'),
  },
  '.drawer-header': {
    display: 'flex',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: '1rem',
    padding: '1rem',
    paddingRight: '1.75rem',
  },
  '.drawer-footer': {
    display: 'flex',
    width: '100%',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: '1rem',
    alignSelf: 'stretch',
    padding: '1rem',
    paddingBottom: '1.25rem',
  },
  '.drawer-title': {
    ...h2Styles(theme),
    color: theme('textColor.default'),
  },
  '.drawer-description': {
    ...textContentParagraphStyles(theme),
    color: theme('textColor.subtler'),
  },
})
